version: '3'
services:

  nginx:
    image: nginx:latest
    networks:
      - ci_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
      - database
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - ci_app

  database:
    image: mysql:5.7
    restart: unless-stopped
    # init database
    volumes:
     - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env
    networks:
     - ci_app


networks:
  ci_app:
    driver: bridge
